name: Java_CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          #https://github.com/actions/setup-java#supported-distributions
          distribution: temurin
          java-version: 11.0.21+9
    - name: Build with Maven
      run: mvn -B package --file pom.xml
